In [12]:
import tensorflow as tf

tf.__version__

'2.1.0'

In [13]:
# Create a Tensor: int, float, double, bool, string

tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [60]:
a = tf.constant(1.)

In [61]:
tf.constant(2.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [62]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [63]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [64]:
tf.constant('hello world.')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world.'>

In [65]:
# Tensor Property: device

a = tf.constant([1])
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [66]:
# Tensor Property: device, shape

with tf.device('gpu'):
    b = tf.range(4)   

b.device
b.shape

TensorShape([4])

In [67]:
# To numpy

b.numpy()

array([0, 1, 2, 3], dtype=int32)

In [68]:
# Returns the number of Tensor dimensions

b.ndim

1

In [69]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [70]:
tf.rank(tf.ones([3,4,2,3]))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [71]:
tf.is_tensor(b)

True

In [72]:
b.dtype

tf.int32

In [73]:
b.dtype == tf.int32

True

In [74]:
# Convert

tf.cast(b, dtype=tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [75]:
# tf.Variable

a = tf.range(5)
b = tf.Variable(a)
b.dtype

tf.int32

In [76]:
b.name

'Variable:0'

In [77]:
b.trainable

True

In [78]:
tf.is_tensor(b)

True