In [2]:
import tensorflow as tf

tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [3]:
# tf.zeros

tf.zeros([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [4]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [5]:
tf.zeros([2,3,3])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [6]:
# tf.zeros_like
# Creates a tensor with all elements set to zero

tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [7]:
# tf.ones
# Creates a tensor with all elements set to one (1)

tf.ones([])

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [8]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [12]:
tf.ones([2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [18]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.ones_like(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [21]:
# fill
# Creates a tensor filled with a scalar value

tf.fill([2,2], 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [23]:
# normal
# Outputs random values from a normal distribution

tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.4085686 , -0.19610445],
       [-1.4665695 ,  0.75942   ]], dtype=float32)>

In [26]:
# Outputs random values from a truncated normal distribution

tf.random.truncated_normal([2,2], mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.81752884,  0.21390335],
       [ 0.6171727 , -0.3260904 ]], dtype=float32)>